name: Deriv RSI Bot
on:
  schedule:
    - cron: '*/30 * * * *' # every 30min to save minutes
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: node bot.js
        env:
          DERIV_TOKEN: ${{ secrets.DERIV_TOKEN }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
